### ISSUE TITLE
Midea Homey app combality with different Miedea made brands?

### ISSUE THREAD

**Issue by Tuokki1** [mteutelink/nl.intyme.midea#2]
Hello,

Does this Homey app only work with Midea brand air heat pumps or does it work with all made by Midea devices, regardless of the brand?

Br,

Tuomas

**Comment by mteutelink** [comment]
It does work with rebranded ACs. Mine are Carrier ACs. They need to be capable of the V3 protocol (the discovery only shows V3 capable devices) and you should have a MSmartHome account. 

With kind regards,
Marc
