### ISSUE TITLE
New mode?  Fan

### ISSUE THREAD

**Issue by Zeeker86** [mteutelink/nl.intyme.midea#3]
Hello.
Great app :)

Is it possible to add "Fan" to the list of mode options?
Now it has the mode, Automatic, Heat, Cool, Off.

![image](https://github.com/user-attachments/assets/33ead04b-75f9-4323-bace-2967c050b0f9)

**Comment by mteutelink** [comment]
I am currently working on this support. Will be released tonight (v1.0.9).

**Comment by mteutelink** [comment]
I added FAN and DRY as options. Waiting for confirmation from Homey. V1.0.9

**Comment by Zeeker86** [comment]
That is nice.
Thank you.
