### ISSUE TITLE
After update to 1.0.9 the options to select "mode" has dissaperd in advanced flows

### ISSUE THREAD

**Issue by Zeeker86** [mteutelink/nl.intyme.midea#4]
Hi.
After update to 1.0.9 the card to select mode is no longer available in advanced flows.

![image](https://github.com/user-attachments/assets/150962fb-13a1-48a4-b58a-5815d3088d66)

![image](https://github.com/user-attachments/assets/5ade779a-07d5-4e66-b420-bc965190546b)

**Comment by mteutelink** [comment]
Ah, I see it. Will fix it as soon as possible.Sent from my iPadOn 10 Dec 2024, at 09:58, Zeeker ***@***.***> wrote:﻿
Hi.
After update to 1.0.9 the card to select mode is no longer available in advanced flows.
image.png (view on web)
image.png (view on web)

**Comment by mteutelink** [comment]
I have submitted v1.0.10

**Comment by mteutelink** [comment]
I am sorry, but I can't speak Norwegian, so I haven't added translations other than ENG and NL.
